### PR TITLE
Updated Nal Driver (2010 version) other versions soon

### PR DESCRIPTION
**Pull request by UnrealLord**
I added the newer version of the intel nal driver, the ioctl and structs are same and have been confirmed working by me.

### CODE REVIEW

**Comment by TheCruZ** [comment]
I will check it, I didn't know that intel release more new versions with this vulnerability

**Comment by TheCruZ** [comment]
Not working:
image

Don't look vulnerable, can you recheck how did you do the tests? else I will reject the merge

**Comment by UnrealLord** [comment]
can you add me in discord real quick? unreal#4096

**Comment by UnrealLord** [comment]
edit: so I loaded the existing driver thinking it was the new driver, however the new driver has 1 single check which fails and doesn't allow the the request:
image

I'll work on finding a way to pass this check in the meantime I found another driver from 2010 (not blacklisted yet afaik) which works perfectly fine, ill remove the 2019 driver bytes from my fork and upload the 2010 one which works like a charm.

**Comment by TheCruZ** [comment]
Since go to older version don't make too much sense and about the driver is flagged by EAC or not isn't important because they can add all of them I reject this pull

**Pull request closed without merging**
