### PR TITLE
Security Cookie Fix

### PR DESCRIPTION
**Pull request by Jerem584**
Add the possibility to use non custom entry point (NtProcessStartup) and so the crt (which is useless) but nice, it also can't really fail

### CODE REVIEW

**Comment by Jerem584** [comment]
told you:  https://github.com/TheCruZ/kdmapper/issues/37

seems i got smarter with the time

**Comment by TheCruZ** [comment]
Sorry, I was a bit far from computer this week's
Can i ask why spectre mitigation was disabled? in any case looks good but i didn't got time to test ti

**Comment by Jerem584** [comment]
Hello, 

conflict with my personal visual studio installation, nothing much serious

**Comment by Jerem584** [comment]
I also didn't check if it would work with bigger drivers. But it worked fine with the HelloWorld driver

**Comment by TheCruZ** [comment]
Merged without the extra changes https://github.com/TheCruZ/kdmapper/pull/114

**Pull request closed without merging**
